case_name: RAE-2822
description: profile RAE-2822 subsomic 0.73 M
tag_case: 
  - subsonic
  - profile
soft: Lazurit
proc_per_task: 160
task_to_calculation: ALL
tasks:
  3D_y_1:
    extends: "examples/presets/task:task"
  3D_y_2:
    extends: "examples/presets/task:task"
  3D_y_5:
    extends: "examples/presets/task:task"